disabled_rules:
  - trailing_whitespace
  - opening_brace
  - statement_position
  - unused_closure_parameter
  - trailing_comma

opt_in_rules:
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - Build
  - DerivedData

line_length:
  warning: 120
  error: 200
