version = 1

SPDX-PackageName = "magiclane-maps-sdk-examples-for-ios"
SPDX-PackageSupplier = "magiclane-developer@users.noreply.github.com"
SPDX-PackageDownloadLocation = "https://github.com/magiclane/magiclane-maps-sdk-examples-for-ios"
SPDX-PackageComment = "A collection of sample projects to support application development with the Magic Lane Maps SDK for iOS."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "1995-2025 Magic Lane International B.V. <info@magiclane.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/BalloonMarker.swift"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 Daniel Cohen Gindi & Philipp Jahoda"
SPDX-License-Identifier = "Apache-2.0"
